# Generated by Django 3.0.2 on 2020-01-12 21:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CarMaker',
            fields=[
                ('make_id', models.CharField(max_length=30, primary_key=True, serialize=False, verbose_name='id производителя')),
                ('make_display', models.CharField(max_length=30, verbose_name='Имя производителя')),
                ('make_is_common', models.CharField(choices=[('1', 'распространён'), ('0', 'не распространён')], max_length=1, verbose_name='Распространённость производителя')),
                ('make_country', models.CharField(max_length=30, verbose_name='Страна производителя')),
            ],
            options={
                'verbose_name': 'Производитель',
                'verbose_name_plural': 'Производители',
            },
        ),
    ]
